version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"


  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  product-service:
    build: ./services/products/docker
    ports:
      - "5002:5002"

    environment:
      - MONGO_URI=mongodb://mongo:27017/products-db

    depends_on:
      - mongo
      - redis


# // learn and drun : docker-compose build;  then ;  docker-compose up